server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}

jerseyClient:
  timeout: 45000ms
  connectionTimeout: 1500ms
  connectionRequestTimeout: 1500ms
  gzipEnabled: true

viewRendererConfiguration:
  freemarker:
    strict_syntax: yes
    whitespace_stripping: yes
    default_encoding: UTF-8

logging:
  level: INFO
  loggers:
    zpalmer.tumbldown: DEBUG
    org.glassfish.jersey.logging.LoggingFeature: DEBUG
  appenders:
    - type: console
      timeZone: UTC
    - type: file
      timeZone: UTC
      currentLogFilename: ./logs/dev.log
      archive: false
      layout:
        type: json

metrics:
  reporters:
    - type: console
      timeZone: UTC
      output: stdout
      includes: [zpalmer.tumbldown.resources.SearchResource.displayResultsPage]
  reportOnStop: true
