jerseyClient:
  timeout: 45000ms
  connectionTimeout: 1500ms
  connectionRequestTimeout: 1500ms
  gzipEnabled: true

logging:
  level: INFO
  loggers:
    zpalmer.tumbldown: DEBUG
    org.glassfish.jersey.logging.LoggingFeature: DEBUG
  appenders:
    - type: console
    - type: file
      currentLogFilename: ./logs/dev.log
      archive: false
      layout:
        type: json

viewRendererConfiguration:
    freemarker:
        strict_syntax: yes
        whitespace_stripping: yes
        default_encoding: UTF-8
