<br/><br/><br/><br/>
<div name="footer">
    <small><a target="_blank" rel="noopener noreferrer" href="mailto:tumbldown@protonmail.ch?subject=Tumbldown Bug Report or Feature Request&body=Please let me know what your issue is here. Your email will not be stored except with a secure email provider, and it will not be used in any way or for any purpose.">
        Report a bug or request a feature
    </a></small> 📧
</div>